In [3]:
import numpy as np 
import matplotlib.pyplot as plt

Matrix Addition

In [84]:
A = np.random.rand(3,3)
print(f"A = \n{A}\n")
B = np.random.rand(3,3)
print(f"B = \n{B}\n")
print(f"A + B = \n{A+B}\n")

A = 
[[0.19673261 0.80415082 0.70867527]
 [0.48473056 0.54912771 0.00208187]
 [0.82335402 0.76530067 0.61008196]]

B = 
[[0.45332425 0.04074929 0.10778829]
 [0.70841256 0.79118106 0.58725339]
 [0.75563146 0.67162469 0.62194142]]

A + B = 
[[0.65005686 0.84490012 0.81646356]
 [1.19314312 1.34030877 0.58933526]
 [1.57898548 1.43692536 1.23202338]]



Dot Product

In [85]:
C = np.random.rand(3,3)
print(f"A.B - C = \n {np.dot(A,B)-C}")


A.B - C = 
 [[ 0.7190618   0.21122573  0.23791487]
 [-0.16259479 -0.14349388  0.19653793]
 [ 0.95300129  0.52355365  0.56650289]]


Element Wise Multiplication 

In [86]:
print(f"A (element-wise multiplication) B + C^T = \n {A*B + np.transpose(C)}")

A (element-wise multiplication) B + C^T = 
 [[0.5644734  0.80568558 0.49977768]
 [1.25237292 1.03356343 0.52645754]
 [1.3184376  0.69347708 0.73054092]]


A^T B

In [87]:
A = np.array([1,2,3]).reshape((3,1))
B = np.array([1,2,3]).reshape((3,1))
print(f" A = \n {A} \n and B = \n {B} \n A^T B = \n {np.dot(np.transpose(A),B)}")

 A = 
 [[1]
 [2]
 [3]] 
 and B = 
 [[1]
 [2]
 [3]] 
 A^T B = 
 [[14]]


Inverse

In [88]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
x = np.array([1, 2, 3]).reshape((-1,1))

result = np.linalg.solve(A, x)
print(np.dot(np.linalg.inv(A),B))
print(result)


[[-3.33333333e-01]
 [ 6.66666667e-01]
 [ 1.11022302e-16]]
[[-0.33333333]
 [ 0.66666667]
 [-0.        ]]


AB = (B^TA^T)^T

In [89]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
x = np.array([1, 2, 3])

result = np.linalg.solve(A.T, x.T).T
print(result)


[ 1.  0. -0.]


Summation of a row in the given matrix

In [90]:
A = np.random.rand(6,6)
i = np.random.randint(1,6)
print(f"A = \n {A}\ni = {i},\n")
print(np.sum(A[i,2::2]))

A = 
 [[0.62505177 0.20993501 0.25472359 0.09109655 0.15485234 0.55964393]
 [0.48259411 0.08427352 0.50145271 0.03474063 0.13400269 0.38429734]
 [0.27394177 0.95849582 0.50074324 0.16973655 0.99413205 0.9250505 ]
 [0.50025368 0.28731437 0.9002156  0.02148037 0.59110098 0.77210887]
 [0.26011134 0.68751359 0.63322487 0.21500219 0.71411739 0.87762804]
 [0.2441004  0.92445757 0.44821242 0.3635826  0.81444711 0.70476615]]
i = 2,

1.4948752930426992


Custom Summation

In [91]:
A = np.random.rand(6,6)*10

c, d = 2,6
print(f"A = \n{A}\n c, d = {c,d} \nAnswer = \n{np.mean(A[np.nonzero((A >= c) & (A <= d))])}") 
c, d = 0, 0

A = 
[[3.5567636  7.47394686 2.36845926 0.76307985 5.04408754 6.48964267]
 [7.4167176  9.35608843 4.7580363  5.52505232 2.80362573 0.15071126]
 [5.84756707 8.47231865 4.69884341 8.04538127 7.05499644 9.41313601]
 [2.0625037  3.14674556 1.31117147 4.58072299 1.64069099 7.26090794]
 [3.34626978 8.19762702 7.95211316 9.59237854 7.80105379 5.00834979]
 [5.4357392  4.25496705 3.71371696 2.45042182 6.69028735 4.18382895]]
 c, d = (2, 6) 
Answer = 
4.043650057270582


Sorting

In [92]:
A = np.random.rand(6,6)*10
k = np.random.randint(0,5)

val, vec = np.linalg.eig(A)
i = np.argsort(val)[::-1][:k]
print(vec[:,i])

[[ 0.36604971+0.j -0.08519501+0.j  0.59117434+0.j]
 [ 0.38182548+0.j -0.02809769+0.j -0.64889952+0.j]
 [ 0.43616391+0.j  0.05748469+0.j -0.09014597+0.j]
 [ 0.4736742 +0.j  0.28407993+0.j  0.02839107+0.j]
 [ 0.28827803+0.j  0.28808143+0.j -0.17386786+0.j]
 [ 0.47170594+0.j -0.90827062+0.j  0.43621088+0.j]]


Multivariate Normal Distribution

In [109]:
n, m, s, k  = np.random.randint(3,8), np.random.randint(1,6),  np.random.randint(1,6), np.random.randint(1,6)
x = np.random.rand(n,1)
print(f'n = {n},\tm = {m},\ts = {s}, \tk = {k}, \nx = \n{x}')

z = np.ones((x.shape))
mean = x + m*z
cov = s*np.identity(n)

answer = np.random.multivariate_normal(mean.flatten(), cov, k)
print(answer)


n = 6,	m = 4,	s = 4, 	k = 5, 
x = 
[[0.63401866]
 [0.89262795]
 [0.49469602]
 [0.80473759]
 [0.11191846]
 [0.33949438]]
[[4.32289843 4.52116407 3.12678975 5.83210396 0.01145984 5.13305952]
 [4.35015882 2.4665963  1.5246     2.45287717 2.24254944 4.75368938]
 [4.61510277 1.1098373  1.25836314 7.98779105 6.38992563 2.30113793]
 [4.45406634 5.65088468 2.96081279 5.20358511 3.74486763 2.62056847]
 [5.22987525 5.48166628 2.2488019  3.76931408 4.80209231 1.56802567]]


In [155]:
A = np.random.rand(4,4)*10
B = np.zeros((A.shape))
for k,row in enumerate(A):
    print(k)
    x = np.random.randint(0,A.shape[0])
    B[k,:] = A[x,:]
    A[x,:] = np.zeros((A[x,:].shape))
    y = A[np.nonzero(A)]
    A = np.reshape(y,(A.shape[0]-1, A.shape[1]))
    # print(A)
    print(B)


0
[[2.32048725 1.54310307 8.79467309 3.28285882]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]
1
[[2.32048725 1.54310307 8.79467309 3.28285882]
 [7.49599284 4.12364005 8.18177187 3.80331438]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]
2
[[2.32048725 1.54310307 8.79467309 3.28285882]
 [7.49599284 4.12364005 8.18177187 3.80331438]
 [6.76957145 9.82609407 7.06054872 4.04414867]
 [0.         0.         0.         0.        ]]
3
[[2.32048725 1.54310307 8.79467309 3.28285882]
 [7.49599284 4.12364005 8.18177187 3.80331438]
 [6.76957145 9.82609407 7.06054872 4.04414867]
 [7.42276079 6.9394272  6.35883581 6.16735751]]


Normalizing

In [161]:
n = np.random.randint(3,8)
A = np.random.rand(n,1)*10
print(A)
B = np.zeros_like(A)
mean = np.mean(A)
std = np.std(A)

for k,i in enumerate(A):
    B[k] = (i - mean)/std

print(B)
    

[[9.35574028]
 [8.16820008]
 [0.50976732]
 [9.63916087]
 [7.70278445]
 [1.12636013]]
[[ 0.86448025]
 [ 0.5507325 ]
 [-1.47262305]
 [ 0.93935988]
 [ 0.42776983]
 [-1.30971942]]


Basics: numpy 

In [181]:
n = np.random.randint(3,8)
m = np.random.randint(3,8)
# A = np.random.rand(m,n)*10
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])

A = A[:,:, np.newaxis]
A = np.repeat(A, A.shape[1], axis=2)
print(A)
swapA = np.swapaxes(A, 0, 2)
print(np.linalg.norm(A-swapA, axis=1))

[[[ 1  1  1]
  [ 2  2  2]
  [ 3  3  3]]

 [[ 4  4  4]
  [ 5  5  5]
  [ 6  6  6]]

 [[ 7  7  7]
  [ 8  8  8]
  [10 10 10]]]
[[ 0.          5.19615242 11.        ]
 [ 5.19615242  0.          5.83095189]
 [11.          5.83095189  0.        ]]


Age Regressor

In [1]:
def linear_regression(X, y):
    X = np.transpose(X)
    print(X.shape)
    print(y.shape)
    X_XT = np.matmul(X,np.transpose(X))
    XY = np.matmul(X,y)
    w = np.linalg.solve(X_XT,XY)
    return w, X



def train_age_regressor():
    # Load data
    X_tr = np.reshape(np.load(r"D:\WPI\Academics\Deep_Learning\DL\HW01\age_regression_Xtr.npy"), (-1, 48*48))
    ytr = np.load(r"D:\WPI\Academics\Deep_Learning\DL\HW01\age_regression_ytr.npy").reshape(-1,1)
    X_te = np.reshape(np.load(r"D:\WPI\Academics\Deep_Learning\DL\HW01\age_regression_Xte.npy"), (-1, 48*48))
    yte = np.load(r"D:\WPI\Academics\Deep_Learning\DL\HW01\age_regression_yte.npy").reshape(-1,1)

    w, X = linear_regression(X_tr, ytr)
    # print(w)
    yhat = np.matmul(X_tr,w)
    y_tr_hat = np.square(yhat - ytr)
    FMSE_tr = (np.mean(y_tr_hat)/2).reshape(-1,1)
    print(FMSE_tr)
    yhat_te = np.square(np.matmul(X_te,w)-yte)
    FMSE_te = (np.mean(yhat_te)/2).reshape(-1,1)
    print(f"FMSE of test = {FMSE_te}")


In [4]:
train_age_regressor()

(2304, 5000)
(5000, 1)
[[50.46528793]]
FMSE of test = [[268.74474836]]


Using Stochastic Gradient Descend in Numpy

In [1]:
import numpy as np
from cmath import inf

In [2]:
def linear_regression(X, y):
    print(X.shape)
    print(y.shape)
    X_XT = np.matmul(X,np.transpose(X))
    XY = np.matmul(X,np.transpose(y))
    w = np.linalg.solve(X_XT,XY)
    return w, X


def mean_square_error(y_hat, y):
        sq_error = np.square(y_hat-y)
        mse = (np.mean(sq_error))/2
        return mse


def train_age_regressor1():
    # Load data
    X_tr = np.reshape(np.load(r"D:\WPI\Academics\Deep_Learning\DL\HW01\age_regression_Xtr.npy"), (-1, 48*48))
    ytr = np.load(r"D:\WPI\Academics\Deep_Learning\DL\HW01\age_regression_ytr.npy")
    X_te = np.reshape(np.load(r"D:\WPI\Academics\Deep_Learning\DL\HW01\age_regression_Xte.npy"), (-1, 48*48))
    yte = np.load(r"D:\WPI\Academics\Deep_Learning\DL\HW01\age_regression_yte.npy")

    X = X_tr.T
    # print(f'shape of Xtr and ytr = {X.shape, ytr.shape}')
    
    ## Randomly permutate over the indexes of the training data
    idx = np.random.permutation(X.shape[1]).reshape(1,-1)
    print(f'shape of idx = {idx.shape}')
    c = int(idx.shape[1]*0.8)
    Xtrain = X[:,:c]
    ytrain = ytr[:c]
    Xvalid = X[:,c:]
    yvalid = ytr[c:]
    # print(f'shape of Xtrain and ytrain= {Xtrain.shape, ytrain.shape}')
    # print(f'shape of Xvalid and yvalid= {Xvalid.shape, yvalid.shape}')

    return Xtrain, np.transpose(ytrain).reshape(1,-1), Xvalid, np.transpose(yvalid).reshape(1,-1), X_te, np.transpose(yte).reshape(1,-1)

    

In [3]:
Xtr, ytr, Xval, yval, Xte, yte = train_age_regressor1()
print(f'shape of Xtrain and ytrain= {Xtr.shape, ytr.shape}')
print(f'shape of Xval and yval= {Xval.shape, yval.shape}')
print(f'shape of Xte and yte= {Xte.shape, yte.shape}')


shape of idx = (1, 5000)
shape of Xtrain and ytrain= ((2304, 4000), (1, 4000))
shape of Xval and yval= ((2304, 1000), (1, 1000))
shape of Xte and yte= ((2500, 2304), (1, 2500))


In [4]:
# w, X = linear_regression(Xtr, ytr)
# print(w.shape, X.shape)
# yhat = np.matmul(np.transpose(X),w)
# mse = mean_square_error(ytr,yhat)


In [6]:
def Fmse(X, y, w, bias):
    # print("fmse wei",w.shape)
    yhat = np.matmul(np.transpose(X), w) + bias
    temp = np.square(yhat - y)
    fmse = np.mean(temp)/2
    return fmse

def grad_weights(X, y, bias, w, alpha):
    # print("gradw wei",w.shape)
    # print("grad w chya aat X",X.shape)
    yhat = np.matmul(np.transpose(X), w) + bias - np.transpose(y)
    # print("yhat",yhat.shape)
    temp2 = np.matmul(X, yhat)/X.shape[1]
    # print("temp2",temp2.shape)    
    L2reg = np.dot((alpha/2),w)
    grad_mse = (temp2/X.shape[1]) +L2reg
    return grad_mse

def grad_bias(X, y, w, bias):
    # print("gradb wei",w.shape)
    yhat = np.matmul(np.transpose(X), w) + bias - np.transpose(y)
    # print("yhat in grad b = ", yhat.shape)
    temp = np.mean(np.matmul(X, yhat))
    # print("temp in b = ", temp.shape)
    return temp  



def SGD(epoch, X,  mini_batch, lr, alpha, w_init, y, bias):
    for i in range(epoch):
        # print('epoch',i)
        mini_batch_size = X.shape[1]/mini_batch
        # print(mini_batch_size)
        # idx = np.random.permutation(X.shape[1]).reshape(1,-1)
        start = 0
        ws = w_init
        end = int(mini_batch_size)
        for j in range(int(mini_batch_size)):
            # print("mini_sgd chya aat", j)
            train = X[:, start:end]
            label = y[:, start:end]
            # print(train.shape, label.shape, ws.shape)
            grad_w = grad_weights(train, label, bias, ws, alpha)
            grad_b = grad_bias(train, label, ws, bias)
            # print("ws1", ws.shape)
            # print("grad_w",grad_w.shape)
            # print("sgd chay aat b navin = ", grad_b.shape)
            w_new = ws - lr*grad_w
            # print("ws2",w_new.shape)
            b_new = bias - np.dot(lr,grad_b)
            # print("new bias in sgd", b_new.shape)

            ws = w_new
            bias = b_new
            start = end
            end = end + int(mini_batch_size)
            # print(start, end)

    fmse_epoch = Fmse(X, y, ws, bias)
    return fmse_epoch, w_new, b_new

In [ ]:
##Random initializations for hyper-parameters
w = np.zeros((Xtr.shape[0],1))
for i in range(w.shape[0]):
    w[i] = np.random.randint(-10,10)
# print('weightsize',w_init.shape)

bias = 0

epochs = [100, 250, 500, 1000]
lrs = [0.001, 0.005, 0.007, 0.009]
alphas = [0.1, 0.5, 1.0, 2.0]
mini_batch = [25, 50, 100, 250]
fmse_init = inf


for epoch in epochs:
    print("number of epochs", epoch)
    for mb in mini_batch:
        # print("mb",mb)
        for lr in lrs:
            # print("lrs",lr)
            for alpha in alphas:
                # print("alpha", alpha)
                # print("Xtr", Xtr.shape, "ytr", ytr.shape)
                fmse_epoch, w, b = SGD(epoch, Xtr, mb, lr, alpha, w, ytr, bias)            #def SGD(epoch, X,  mini_batch, lr, alpha, w_init, y, bias):
                fmse_epoch_of_valid = Fmse(Xval, yval, w, b)
                if fmse_epoch_of_valid < fmse_init:
                    print("Lowest Fmse for epochs (m)",epoch," Learning rate",lr,"alpha", alpha," mini_batch_size",mb)
                    # best_w = w
                    # best_b = b
                    best_alpha = alpha
                    best_mini_batch = mb
                    best_lr = lr
                    best_epochs = epoch

w_init = np.zeros((Xtr.shape[0],1))
for i in range(w_init.shape[0]):
    w_init[i] = np.random.randint(-10,10)

bias = 0
fmse, w, b = SGD(best_epochs, Xtr, best_mini_batch, best_lr, best_alpha, w_init, ytr, bias)

print(f'Fmse = {fmse}')

                